###
#1	Add a New Post

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "New Post",
    "sender": "I sent this",
    "content": "This is the content of the post."
}
###
#2.	Get All Posts
GET http://localhost:3000/posts

###
#3.	Get a Post by ID
GET http://localhost:3000/posts/6739f43a19b0108c81d43fbb

###
#4.	Get Posts by Sender: 

GET http://localhost:3000/posts?sender=Gaya vish


###
#5. Update a Post: 
PUT http://localhost:3000/posts/674048e7f4934155c7143552
Content-Type: application/json

{
    "title": "Updated Title",
    "sender": "Updated Owner",
    "content": "Updated Content"
}

###

#1 Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "674048e7f4934155c7143552",
    "user": "Barbie",
    "message": "Pink is my favorite color."
}

###

# Get a comment by coment ID
GET http://localhost:3000/comments/674054ac7bdd6553eea58e40

###

# Get all comments
GET http://localhost:3000/comments

###!!!!
# Get comments by post ID
GET http://localhost:3000/comments?postId=674048e7f4934155c7143552

###
# Update a comment
PUT http://localhost:3000/comments/674054ac7bdd6553eea58e40
Content-Type: application/json

{
    "message": "Updated comment."
}

###

# Delete a comment
DELETE http://localhost:3000/comments/674051ff6eae7051ad4c2f01



